dist: xenial
language: java

cache:
  directories:
    - $HOME/.m2

matrix:
  include:
    - jdk: openjdk8
    - jdk: openjdk11

sudo: false

before_install:
  - cp src/build/travis-toolchains.xml ~/.m2/toolchains.xml
  - wget https://archive.apache.org/dist/maven/maven-3/3.6.1/binaries/apache-maven-3.6.1-bin.zip
  - unzip -qq apache-maven-3.6.1-bin.zip
  - export M2_HOME=$PWD/apache-maven-3.6.1
  - export PATH=$M2_HOME/bin:$PATH

script: mvn -B -fae clean install
