name: ci

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java-version: [ 11, 17 ]

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v2
      id: build_java
      with:
        distribution: temurin
        java-version: ${{ matrix.java-version }}
        cache: maven
    - name: Build
      run: |
        make deploy deploy-docs
